[get_exercises]
summary = "Get - Rota retorna todos os exercícios cadastrados"
description = """
## Retorna todos os exercícios cadastrados no banco de dados.
Os exercícios são retornados em ordem dos id, com os seguintes campos:
"""
resp_description = "Retorna uma lista com todos os exercícios cadastrados no banco de dados."


[get_exercises_difficulty]
summary = "Get - Rota retorna todos os exercícios cadastrados filtrados por dificuldade"
description ="""
## Retorna todos os exercícios cadastrados no banco de dados.
Os exercícios são retornados em ordem dos id, com os seguintes campos:
"""
resp_description = "Retorna uma lista com todos os exercícios cadastrados no banco de dados filtrados por dificuldade."

[get_exercises_muscle_group]
summary = "Get - Rota retorna todos os exercícios cadastrados filtrados por grupo muscular"
description = """
## Retorna todos os exercícios cadastrados no banco de dados.
Os exercícios são retornados em ordem dos id, com os seguintes campos:
"""
resp_description = "Retorna uma lista com todos os exercícios cadastrados no banco de dados filtrados por grupo muscular."

[get_exercises_equipment_needed]
summary = "Get - Rota retorna todos os exercícios cadastrados filtrados por equipamento necessário"
description = """
## Retorna todos os exercícios cadastrados no banco de dados.
Os exercícios são retornados em ordem dos id, com os seguintes campos:
"""
resp_description = "Retorna uma lista com todos os exercícios cadastrados no banco de dados filtrados por equipamento necessário."

[create_exercise]
summary = "Post - Rota para criar um novo exercício"
description = """
## Cria um novo exercício no banco de dados.
Os exercícios são retornados em ordem dos id, com os seguintes campos:
"""
resp_description = "Retorna o exercício criado com sucesso."


[update_exercise]
summary = "Patch - Rota para atualizar um exercício existente"
description = """
## Atualiza um exercício existente no banco de dados.
Os exercícios são retornados em ordem dos id, com os seguintes campos:
"""
resp_description = "Retorna o exercício atualizado com sucesso."

[update_exercise_midias]
summary = "Patch - Rota para atualizar as mídias de um exercício existente"
description = """
## Atualiza as mídias de um exercício existente no banco de dados.
Os exercícios são retornados em ordem dos id, com os seguintes campos:
"""
resp_description = "Retorna o exercício atualizado com sucesso."

[delete_exercise]
summary = "Delete - Rota para deletar um exercício existente"
description = """
## Deleta um exercício existente no banco de dados.
Os exercícios são retornados em ordem dos id, com os seguintes campos:
"""
resp_description = "Remove o exercício com sucesso não retornando nada."