[get_exercises]
summary = "Get - Rota para listar todos os exercícios cadastrados"
description = """
## Lista todos os exercícios cadastrados no banco de dados.

### Comportamento:
- Retorna uma lista de exercícios ordenados pelo ID.

### Códigos de Resposta:
- 200: Lista de exercícios retornada com sucesso.
- 500: Erro interno do servidor.
"""
resp_description = "Retorna uma lista com todos os exercícios cadastrados no banco de dados."


[get_exercises_difficulty]
summary = "Get - Rota para listar exercícios filtrados por dificuldade"
description = """
## Lista exercícios cadastrados filtrados por dificuldade.

### Parâmetros:
- **`difficulty`** (obrigatório): Nível de dificuldade do exercício (inteiro).

### Comportamento:
- Retorna uma lista de exercícios que correspondem ao nível de dificuldade especificado.
- Caso nenhum exercício seja encontrado, retorna um erro 404.

### Códigos de Resposta:
- 200: Lista de exercícios retornada com sucesso.
- 404: Nenhum exercício encontrado para a dificuldade especificada.
- 500: Erro interno do servidor.
"""
resp_description = "Retorna uma lista com todos os exercícios cadastrados no banco de dados filtrados por dificuldade."


[get_exercises_muscle_group]
summary = "Get - Rota para listar exercícios por grupo muscular"
description = """
## Lista exercícios que trabalham grupos musculares específicos.

### Parâmetros de consulta:
- **`muscle_group`** (obrigatório): Um ou mais grupos musculares para filtrar os exercícios.

#### Exemplos:
- `?muscle_group=peito&muscle_group=perna`
- `?muscle_group=peito,perna`

### Comportamento:
- Retorna uma lista de exercícios que correspondem aos grupos musculares especificados.
- Caso nenhum exercício seja encontrado, retorna um erro 404.

### Códigos de Resposta:
- 200: Lista de exercícios retornada com sucesso.
- 404: Nenhum exercício encontrado para os grupos musculares especificados.
- 500: Erro interno do servidor.
"""
resp_description = "Retorna uma lista de exercícios que correspondem aos grupos musculares especificados."


[get_exercises_equipment_needed]
summary = "Get - Rota para listar exercícios filtrados por equipamento necessário"
description = """
## Lista exercícios cadastrados filtrados por equipamento necessário.

### Parâmetros de consulta:
- **`equipment`** (obrigatório): Lista de equipamentos necessários para filtrar os exercícios.

### Comportamento:
- Retorna uma lista de exercícios que utilizam os equipamentos especificados.
- Caso nenhum exercício seja encontrado, retorna um erro 404.

### Códigos de Resposta:
- 200: Lista de exercícios retornada com sucesso.
- 404: Nenhum exercício encontrado para os equipamentos especificados.
- 500: Erro interno do servidor.
"""
resp_description = "Retorna uma lista com todos os exercícios cadastrados no banco de dados filtrados por equipamento necessário."


[create_exercise]
summary = "Post - Rota para criar um novo exercício"
description = """
## Cria um novo exercício no banco de dados.

### Parâmetros:
- **`payload`** (obrigatório): Dados do exercício a ser criado, incluindo nome, dificuldade, grupos musculares, equipamentos necessários, entre outros.

### Restrições:
- O nome do exercício deve ser único.

### Comportamento:
- Caso o nome do exercício já exista, retorna um erro 409.
- Caso contrário, cria o exercício e retorna os dados do exercício criado.

### Códigos de Resposta:
- 201: Exercício criado com sucesso.
- 409: Nome do exercício já existe.
- 500: Erro interno do servidor.
"""
resp_description = "Retorna o exercício criado com sucesso."


[update_exercise]
summary = "Patch - Rota para atualizar um exercício existente"
description = """
## Atualiza um exercício existente no banco de dados.

### Parâmetros:
- **`exercise_id`** (obrigatório): ID do exercício a ser atualizado.
- **`payload`** (obrigatório): Dados a serem atualizados no exercício. Apenas os campos fornecidos serão alterados.

### Restrições:
- O exercício deve existir no banco de dados.

### Comportamento:
- Caso o exercício não seja encontrado, retorna um erro 404.
- Caso o exercício seja encontrado, os campos fornecidos serão atualizados.

### Códigos de Resposta:
- 200: Exercício atualizado com sucesso.
- 404: Exercício não encontrado.
- 500: Erro interno do servidor.
"""
resp_description = "Retorna o exercício atualizado com sucesso."


[update_exercise_midias]
summary = "Patch - Rota para atualizar as mídias de um exercício existente"
description = """
## Atualiza as mídias de um exercício existente no banco de dados.

### Parâmetros:
- **`exercise_id`** (obrigatório): ID do exercício cujas mídias serão atualizadas.
- **`payload`** (obrigatório): Dados das mídias a serem atualizadas. Apenas os campos fornecidos serão alterados.

### Restrições:
- O exercício deve existir no banco de dados.

### Comportamento:
- Caso o exercício não seja encontrado, retorna um erro 404.
- Caso o exercício seja encontrado, as mídias fornecidas serão atualizadas.

### Códigos de Resposta:
- 200: Mídias do exercício atualizadas com sucesso.
- 404: Exercício não encontrado.
- 500: Erro interno do servidor.
"""
resp_description = "Retorna o exercício atualizado com sucesso."


[delete_exercise]
summary = "Delete - Rota para remover um exercício existente"
description = """
## Remove um exercício existente do banco de dados.

### Parâmetros:
- **`exercise_id`** (obrigatório): ID do exercício a ser removido.

### Restrições:
- O exercício deve existir no banco de dados.

### Comportamento:
- Caso o exercício não seja encontrado, retorna um erro 404.
- Caso o exercício seja encontrado, ele será removido permanentemente.

### Códigos de Resposta:
- 200: Exercício removido com sucesso.
- 404: Exercício não encontrado.
- 500: Erro interno do servidor.
"""
resp_description = "Exclui o exercício com sucesso e não retorna nenhum conteúdo."