"""migrations

Revision ID: 3480d5da8caf
Revises: 9fe39a02ec5c
Create Date: 2025-05-12 13:15:29.327304
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3480d5da8caf'
down_revision: Union[str, None] = '9fe39a02ec5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('muscle_group', sa.JSON(), nullable=True)
        )
        batch_op.drop_column('equipment_needed')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('equipment_needed', sqlite.JSON(), nullable=True)
        )
        batch_op.drop_column('muscle_group')

    # ### end Alembic commands ###
