"""migrations

Revision ID: 8c4b104d86b5
Revises: f7c7f4e154be
Create Date: 2025-05-14 14:15:55.244107
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c4b104d86b5'
down_revision: Union[str, None] = 'f7c7f4e154be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cardio_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_user_cardio_logs_cardio_exercise_id',
            'cardio_exercises',
            ['cardio_exercise_id'],
            ['id'],
        )

    with op.batch_alter_table('user_hiit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_user_hiit_logs_workout_exercise_id',
            'workout_exercises',
            ['workout_exercise_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_hiit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_user_hiit_logs_workout_exercise_id', type_='foreignkey'
        )

    with op.batch_alter_table('user_cardio_logs', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_user_cardio_logs_cardio_exercise_id', type_='foreignkey'
        )

    # ### end Alembic commands ###
