"""migrations

Revision ID: 9fe39a02ec5c
Revises: bf35d3ca6280
Create Date: 2025-05-12 13:11:51.117286
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9fe39a02ec5c'
down_revision: Union[str, None] = 'bf35d3ca6280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('equipment_needed', sa.JSON(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('equipment_needed')

    # ### end Alembic commands ###
